### ISSUE TITLE
Inline code is not styled properly

### ISSUE THREAD

**Issue by mirhmousavi** [nanxiaobei/hugo-paper#226]
The inline code does not follow the style of block-level code

![Screenshot from 2024-05-09 11-24-09](https://github.com/nanxiaobei/hugo-paper/assets/2023858/c12f23f2-822c-4d7f-88a3-0a3fe457c648)

How it looks

![Screenshot from 2024-05-09 11-07-49](https://github.com/nanxiaobei/hugo-paper/assets/2023858/81c90852-e802-4692-a8bb-f8168c66f4be)

Config

```toml
baseURL = "..."
languageCode = 'en-us'
title = '...'

[markup.highlight]
    linenos = true
    style = 'monokailight'
```

Great theme btw.
