### ISSUE TITLE
带有行数的代码显示效果不好

### ISSUE THREAD

**Issue by xNathan** [nanxiaobei/hugo-paper#23]
Hugo 版本： v0.54.0
hugo-paper版本：3.0 (0a22cc5)

`config.toml` 代码高亮配置：

```toml
PygmentsCodeFences = true
PygmentsUseClasses = true
PygmentsCodefencesGuessSyntax = true
PygmentsOptions = "linenos=table
```

文章中任意插入一代码块，例如：

```python
import this

print("Hello World")
```

行号不能很好地展示，与代码之间有一段距离，并且和前后段落的间距也很大。

类似issue #12 

效果如图：

<img width="621" alt="图片" src="https://user-images.githubusercontent.com/12662644/55572263-cfa59b00-5739-11e9-9336-daa115e5ee6f.png">
