### ISSUE TITLE
超链接的能否加个颜色? 像github中readme中那样的.

### ISSUE THREAD

**Issue by Charles-one** [nanxiaobei/hugo-paper#29]
超链接的能否加个颜色? 像github中readme中那样的.
现在加了参考的链接, 很难看出来是链接, 或者能否告诉我
需要修改哪些css?  我可以自己修改. 

最后, 非常感谢提供这么简洁好看的主题.

**Comment by nanxiaobei** [comment]
现在超链接是下划线处理的。
需要修改颜色的话，可以修改 style.css 中的 a 标签的颜色
```css
a {
    color: rgba(0, 0, 0, 0.9);
}
```
若需下划线颜色一致，还需修改
```css
.post-content a {
    box-shadow: 0 1px 0 rgba(0, 0, 0, 0.9);
}
```
box-shadow 的颜色
